### PR TITLE
Fix HTTP web client

### PR DESCRIPTION
**Pull request by aaga**
Replace old JSON/C++ library with ofJson (now part of OF core libs)

### CODE REVIEW

**Comment by armadillu** [comment]
Oh great, less dependencies! Is this PR complete? Happy to merge if it is!

**Comment by aaga** [comment]
Theoretically complete; waiting for Bryan to give it a quick test.

Also looks like it’s not passing CI, but seems to be a Poco thing which I didn’t change

**Comment by armadillu** [comment]
Ok Ill wait then!
Yeah don't worry about CI, I've been neglecting it for a while.

**Comment by whoisbma** [comment]
It's looking good to me, the remote server example is working for me on OSX. Haven't tried MSVC yet.

**Comment by armadillu** [comment]
thx!

**Pull request merged**
